name: Unomi Cluster Setup
on:
  workflow_dispatch:
    inputs:
      domain_hash:
        description: Domain Hash
        require: true
      environment:
        description: Environment
        require: true
      region:
        description: AWS region
        require: true
permissions:
  pull-requests: write
jobs:
  cluster_setup:
    runs-on: ubuntu-latest
    steps:
      - name: Repo checkout
        uses: actions/checkout@v3
      - name: create branch
        run:  git checkout -b unomi-cluster-setup-${{ inputs.domain_hash }}
      - name: create cluster config files
        working-directory: ./scripts
        run:  python create_cluster.py ${{ inputs.environment }} ${{ inputs.domain_hash }} unomi-cluster-setup-${{ inputs.domain_hash }} ${{ inputs.region }}
      - name: Set git identity
        run: |
            git config user.name 'github-actions[bot]'
            git config user.email 'github-actions[bot]@users.noreply.github.com'
      - name: test
        run: git status
      - name: commit the files
        run:  git add -A && git commit -am "add ${{ inputs.domain_hash }} cluster to ${{ inputs.environment }}-${{ inputs.region }}"
      - name: test
        run:  git status
      - name: create a pr
        run:  gh pr create --title "add ${{ inputs.domain_hash }} cluster to ${{ inputs.environment }}-${{ inputs.region }}" --body "" --head unomi-cluster-setup-${{ inputs.domain_hash }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: merge the pr
        run:  gh pr merge unomi-cluster-setup-${{ inputs.domain_hash }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}